/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.senai.sp.jandira.ui;

/**
 *
 * @author 22282229
 */
public class MedicoDialog extends javax.swing.JDialog {

    /**
     * Creates new form MedicoDialog
     */
    public MedicoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detalhesPanel = new javax.swing.JPanel();
        descricaoLabel = new javax.swing.JLabel();
        descricaoTextField = new javax.swing.JTextField();
        codigoLabel = new javax.swing.JLabel();
        codigoTextField = new javax.swing.JTextField();
        adicionarEspecialidadeLabel = new javax.swing.JLabel();
        adicionarEspecialidadeTextField = new javax.swing.JTextField();
        codigoLabel1 = new javax.swing.JLabel();
        codigoTextField1 = new javax.swing.JTextField();
        codigoLabel2 = new javax.swing.JLabel();
        codigoTextField2 = new javax.swing.JTextField();
        codigoLabel3 = new javax.swing.JLabel();
        codigoTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        codigoLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        codigoLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        detalhesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalhes da Especialidades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 255))); // NOI18N
        detalhesPanel.setLayout(null);

        descricaoLabel.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        descricaoLabel.setForeground(new java.awt.Color(255, 0, 102));
        descricaoLabel.setText("Nome do(a) médico(a):");
        detalhesPanel.add(descricaoLabel);
        descricaoLabel.setBounds(220, 40, 146, 17);

        descricaoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoTextFieldActionPerformed(evt);
            }
        });
        detalhesPanel.add(descricaoTextField);
        descricaoTextField.setBounds(200, 60, 390, 22);

        codigoLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        codigoLabel.setForeground(new java.awt.Color(255, 51, 51));
        codigoLabel.setText("Lista de Espcialidades ");
        detalhesPanel.add(codigoLabel);
        codigoLabel.setBounds(10, 150, 160, 20);

        codigoTextField.setEditable(false);
        codigoTextField.setBackground(new java.awt.Color(255, 204, 51));
        codigoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTextFieldActionPerformed(evt);
            }
        });
        detalhesPanel.add(codigoTextField);
        codigoTextField.setBounds(20, 60, 60, 22);

        adicionarEspecialidadeLabel.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        adicionarEspecialidadeLabel.setForeground(new java.awt.Color(255, 51, 51));
        adicionarEspecialidadeLabel.setText("CRM:");
        detalhesPanel.add(adicionarEspecialidadeLabel);
        adicionarEspecialidadeLabel.setBounds(120, 40, 40, 17);

        adicionarEspecialidadeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarEspecialidadeTextFieldActionPerformed(evt);
            }
        });
        detalhesPanel.add(adicionarEspecialidadeTextField);
        adicionarEspecialidadeTextField.setBounds(86, 60, 100, 22);

        codigoLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        codigoLabel1.setForeground(new java.awt.Color(255, 51, 51));
        codigoLabel1.setText("Telefone:");
        detalhesPanel.add(codigoLabel1);
        codigoLabel1.setBounds(20, 90, 70, 20);

        codigoTextField1.setEditable(false);
        codigoTextField1.setBackground(new java.awt.Color(255, 204, 51));
        codigoTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTextField1ActionPerformed(evt);
            }
        });
        detalhesPanel.add(codigoTextField1);
        codigoTextField1.setBounds(20, 110, 110, 22);

        codigoLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        codigoLabel2.setForeground(new java.awt.Color(255, 51, 51));
        codigoLabel2.setText(" E - mail");
        detalhesPanel.add(codigoLabel2);
        codigoLabel2.setBounds(250, 90, 70, 20);

        codigoTextField2.setEditable(false);
        codigoTextField2.setBackground(new java.awt.Color(255, 204, 51));
        codigoTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTextField2ActionPerformed(evt);
            }
        });
        detalhesPanel.add(codigoTextField2);
        codigoTextField2.setBounds(140, 110, 310, 22);

        codigoLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        codigoLabel3.setForeground(new java.awt.Color(255, 51, 51));
        codigoLabel3.setText("Data de nascimento:");
        detalhesPanel.add(codigoLabel3);
        codigoLabel3.setBounds(470, 90, 140, 20);

        codigoTextField3.setEditable(false);
        codigoTextField3.setBackground(new java.awt.Color(255, 204, 51));
        codigoTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTextField3ActionPerformed(evt);
            }
        });
        detalhesPanel.add(codigoTextField3);
        codigoTextField3.setBounds(470, 110, 130, 22);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        detalhesPanel.add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 120, 120);

        codigoLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        codigoLabel4.setForeground(new java.awt.Color(255, 51, 51));
        codigoLabel4.setText("Código");
        detalhesPanel.add(codigoLabel4);
        codigoLabel4.setBounds(20, 40, 70, 20);

        jButton1.setText(">");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        detalhesPanel.add(jButton1);
        jButton1.setBounds(170, 190, 40, 30);

        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        detalhesPanel.add(jButton2);
        jButton2.setBounds(170, 240, 40, 30);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        detalhesPanel.add(jScrollPane2);
        jScrollPane2.setBounds(230, 170, 120, 120);

        codigoLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        codigoLabel5.setForeground(new java.awt.Color(255, 51, 51));
        codigoLabel5.setText("Lista de Espcialidades do médico  ");
        detalhesPanel.add(codigoLabel5);
        codigoLabel5.setBounds(230, 150, 230, 20);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jButton3.setText("Salvar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detalhesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(35, 35, 35)
                .addComponent(jButton3)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detalhesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descricaoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoTextFieldActionPerformed

    private void codigoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTextFieldActionPerformed

    private void adicionarEspecialidadeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarEspecialidadeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarEspecialidadeTextFieldActionPerformed

    private void codigoTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTextField1ActionPerformed

    private void codigoTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTextField2ActionPerformed

    private void codigoTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MedicoDialog dialog = new MedicoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adicionarEspecialidadeLabel;
    private javax.swing.JTextField adicionarEspecialidadeTextField;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JLabel codigoLabel1;
    private javax.swing.JLabel codigoLabel2;
    private javax.swing.JLabel codigoLabel3;
    private javax.swing.JLabel codigoLabel4;
    private javax.swing.JLabel codigoLabel5;
    private javax.swing.JTextField codigoTextField;
    private javax.swing.JTextField codigoTextField1;
    private javax.swing.JTextField codigoTextField2;
    private javax.swing.JTextField codigoTextField3;
    private javax.swing.JLabel descricaoLabel;
    private javax.swing.JTextField descricaoTextField;
    private javax.swing.JPanel detalhesPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
