/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.senai.sp.jandira.ui;

import br.senai.sp.jandira.dao.EspecialodadeDAO;
import br.senai.sp.jandira.model.Especialidade;
import br.senai.sp.jandira.model.OperacaoEnum;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 22282229
 */
public class PaneleEspecialidades extends javax.swing.JPanel {

    private int linha;

    public PaneleEspecialidades() {
        initComponents();
        EspecialodadeDAO.criarListaDeEspecialidades();

        preencherTabela();

    }

    private int getLinha() {
        linha = tableEspecialidade.getSelectedRow();
        return linha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollEspecialidade = new javax.swing.JScrollPane();
        tableEspecialidade = new javax.swing.JTable();
        buttonExcluirEspecialidade = new javax.swing.JButton();
        buttonEditarEspecialidade = new javax.swing.JButton();
        buttonNovoEspecialidade = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Especialidades :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(51, 51, 255))); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 310));
        setLayout(null);

        tableEspecialidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollEspecialidade.setViewportView(tableEspecialidade);

        add(scrollEspecialidade);
        scrollEspecialidade.setBounds(20, 20, 770, 230);

        buttonExcluirEspecialidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/excluir.png"))); // NOI18N
        buttonExcluirEspecialidade.setText("Excluir");
        buttonExcluirEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirEspecialidadeActionPerformed(evt);
            }
        });
        add(buttonExcluirEspecialidade);
        buttonExcluirEspecialidade.setBounds(470, 270, 110, 30);

        buttonEditarEspecialidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/editar.png"))); // NOI18N
        buttonEditarEspecialidade.setText("Editar");
        buttonEditarEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarEspecialidadeActionPerformed(evt);
            }
        });
        add(buttonEditarEspecialidade);
        buttonEditarEspecialidade.setBounds(590, 270, 100, 30);

        buttonNovoEspecialidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/add.png"))); // NOI18N
        buttonNovoEspecialidade.setText("Novo");
        buttonNovoEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNovoEspecialidadeActionPerformed(evt);
            }
        });
        add(buttonNovoEspecialidade);
        buttonNovoEspecialidade.setBounds(700, 270, 90, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExcluirEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExcluirEspecialidadeActionPerformed

        if (getLinha() != -1) {
            excluirEspecialidade(linha);
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "Por favor, selecione a especialidade que vc deseja exluir",
                    "Atenção",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonExcluirEspecialidadeActionPerformed

    private void excluirEspecialidade(int linha) {

        int resposta = JOptionPane.showConfirmDialog(
                this,
                "Vc confirma a exclusão",
                "Atenção",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (resposta == 0) {
            EspecialodadeDAO.excluir(getCodigo());
            preencherTabela(); 
        }

}
         private Integer getCodigo(){
        String codiStr = tableEspecialidade.getValueAt(getLinha(), 0).toString();
        Integer codigo = Integer.valueOf(codiStr);
        return codigo;
    }

private void editarEspecialidade(){

              Especialidade especialidade =  EspecialodadeDAO.getEspecialidade(getCodigo());

            EspecialidadeDialog especialidadeDialog = new EspecialidadeDialog(
                       null, 
                       true,
                        especialidade, OperacaoEnum.EDITAR);
               especialidadeDialog.setVisible(true);
               preencherTabela();
        }
    
    private void buttonEditarEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarEspecialidadeActionPerformed
               
       if(getLinha() !=-1){
           editarEspecialidade();
       }else{
           JOptionPane.showMessageDialog(
                   this,
                   "Por favor escolha uma especialidade de editação",
                   "Especialidade",
                   JOptionPane.WARNING_MESSAGE);
       }
        
        
    }//GEN-LAST:event_buttonEditarEspecialidadeActionPerformed

    private void buttonNovoEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNovoEspecialidadeActionPerformed
        EspecialidadeDialog especialidadeDialog = new EspecialidadeDialog(null, true, OperacaoEnum.ADICIONAR);
        especialidadeDialog.setVisible(true);
        
        preencherTabela();
    }//GEN-LAST:event_buttonNovoEspecialidadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEditarEspecialidade;
    private javax.swing.JButton buttonExcluirEspecialidade;
    private javax.swing.JButton buttonNovoEspecialidade;
    private javax.swing.JScrollPane scrollEspecialidade;
    private javax.swing.JTable tableEspecialidade;
    // End of variables declaration//GEN-END:variables

    private void preencherTabela() {

        
        tableEspecialidade.setModel(EspecialodadeDAO.getTabelaEspecialidades());
        ajustarTabela();
    }
    
    private void ajustarTabela (){
    
    //Impedir que o ususario moviment as colunas
    tableEspecialidade.getTableHeader().setReorderingAllowed(false);
    
    //bloquear alteração da tabela
    tableEspecialidade

.setDefaultEditor(Object.class  

, null);
    
    
    tableEspecialidade.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    tableEspecialidade.getColumnModel().getColumn(0).setPreferredWidth(50);
    tableEspecialidade.getColumnModel().getColumn(1).setPreferredWidth(217);
    tableEspecialidade.getColumnModel().getColumn(2).setPreferredWidth(500);
}
}
